# Settings

## Import packages

In [1]:
#!pip install --upgrade git+https://github.com/m-wrzr/populartimes
#!pip install python-dotenv

Collecting git+https://github.com/m-wrzr/populartimes
  Cloning https://github.com/m-wrzr/populartimes to /private/var/folders/l_/zlzp_vvs4j31hx3pg4j26tch0000gn/T/pip-req-build-e7rv819q
  Running command git clone --filter=blob:none --quiet https://github.com/m-wrzr/populartimes /private/var/folders/l_/zlzp_vvs4j31hx3pg4j26tch0000gn/T/pip-req-build-e7rv819q
  Resolved https://github.com/m-wrzr/populartimes to commit 989f66b63dd1b6a144c5ad4a7c3a200f7f8649ee
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests<3,>2 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from populartimes==2.0) (2.32.3)
Requirement already satisfied: geopy<3,>=2 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from populartimes==2.0) (2.4.1)
Collecting urllib3<2,>=1.21 (from populartimes==2.0)
  Using cached urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from geopy<3,>=2->populartimes==2.0) (2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from requests<3,>2->populartimes==2.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from requests<3,>2->populartimes==2.0) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/spg5/lib/python3.13/site-packages (from requests<3,>2->populartimes==2.0) (2025.4.26)
Using cached urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Building wheels for collected packages: populartimes
  Building wheel for populartimes (pyproject.toml) ... done
  Created wheel for populartimes: filename=populartimes-2.0-py3-none-any.whl size=13609 sha256=04ab29ebc88b049bc3c8de3851b659aa959315be38a5b0e97fb22576aefd4a1f
  Stored in directory: /private/var/folders/l_/zlzp_vvs4j31hx3pg4j26tch0000gn/T/pip-ephem-wheel-cache-sg014qkc/wheels/29/17/f2/498eb2bb3d5fec50c17bd13466d2c32b724537782f3c9afba2
Successfully built populartimes
Installing collected packages: urllib3, populartimes
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.4.0
    Uninstalling urllib3-2.4.0:
      Successfully uninstalled urllib3-2.4.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [populartimes]
Successfully installed populartimes-2.0 urllib3-1.26.20

In [52]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
import math
import itertools
import geopandas as gpd
import matplotlib.patches as mpatches
import requests
import time
import populartimes
import os

from scipy import stats
from scipy.stats import chi2_contingency, pointbiserialr
from geopy.geocoders import Nominatim
from shapely.geometry import Point
from matplotlib.patches import Circle
from dotenv import load_dotenv

pd.set_option('display.precision', 4)

In [54]:
# duplicate the example.env file, rename it as '.env' and put your key in the '.env' file
# DO NOT push the .env file
load_dotenv()
api_key = os.getenv("GOOGLE_API_KEY")

## Self-defined functions

### fetch_google_place_id(api_key, place_name)

In [ ]:
def fetch_google_place_id(api_key, place_name):
    search_url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"
    search_params = {
        "input": place_name,
        "inputtype": "textquery",
        "fields": "place_id",
        "key": api_key
    }
    
    try:
        response = requests.get(search_url, params=search_params, timeout=5)
        response.raise_for_status()
        sres = response.json()
        
        candidates = sres.get("candidates", [])
        if not candidates:
            return False  # No result found
        return candidates[0].get("place_id")
    
    except Exception as e:
        return False  # Error occurred

### gen_place_info_popularity_df

In [103]:
def gen_place_info_popularity_df(response):
    """
    Converts a populartimes.get_id() response into two DataFrames:
    
    - place_info_df: Basic info about the place (ID, name, rating, location, etc.)
    - popularity_df: Hourly popularity data per weekday (hour_0 to hour_23)
    
    Parameters:
        response (dict): Result from populartimes.get_id()
    
    Returns:
        tuple: (place_info_df, popularity_df)
    """
    place_info_df = pd.DataFrame([{
        'place_id': response['id'],
        'name': response['name'],
        'address': response['address'],
        'types': ','.join(response['types']),
        'lat': response['coordinates']['lat'],
        'lon': response['coordinates']['lng'],
        'rating': response['rating'],
        'review_count': response['rating_n'],
        'phone': response.get('international_phone_number', ''),
        'time_spent_min': response.get('time_spent', [None])[0],
        'time_spent_max': response.get('time_spent', [None, None])[1]
    }])

    popularity_rows = []
    for day_data in response.get('populartimes', []):
        row = {'place_id': response['id'], 'day': day_data['name']}
        row.update({f'hour_{hour}': value for hour, value in enumerate(day_data['data'])})
        popularity_rows.append(row)

    popularity_df = pd.DataFrame(popularity_rows)
    
    return place_info_df, popularity_df

# Google API
- Apply for API Key:
  1. [Create a Google Cloud Project](https://console.cloud.google.com/projectcreate?utm_source=Docs_NewProject&utm_content=Docs_elevation-backend&hl=zh-tw&_gl=1*3gdz2p*_ga*MTY0MTk4NDM1My4xNzQ4OTQ2MzEz*_ga_NRWSTWS78N*czE3NDkwNTkyMDUkbzQkZzEkdDE3NDkwNTk5OTYkajQ5JGwwJGgw&inv=1&invt=AbzPGA)
  2. [Enable Places API + Get Your API Key](https://developers.google.com/maps/documentation/places/web-service/get-api-key?)
- [View SKU Usage and Cost Report](https://console.cloud.google.com/billing/01A4EF-B501A6-60B1D3/reports;grouping=GROUP_BY_SKU?inv=1&invt=AbzO6A)
- [Place Details (legacy) – fields and structure](https://developers.google.com/maps/documentation/places/web-service/legacy/details?hl=zh-tw#fields)
- [(❗️Important❗️) Google Maps Platform Pricing (official)](https://mapsplatform.google.com/pricing/)!

In [7]:
restaurant_df = pd.read_csv('dataset/Manhattan_Restaurant_Latest_Inspection_Results_cleaned.csv')
# Use DBA + BUILDING + STREET to generate full name
restaurant_df['full_name'] = restaurant_df['DBA'] + ' ' + restaurant_df['BUILDING'] + ' ' + restaurant_df['STREET']
restaurant_df['INSPECTION DATE'] = pd.to_datetime(restaurant_df['INSPECTION DATE'])

# Remove records with invalid inspection date
restaurant_df = restaurant_df[restaurant_df['INSPECTION DATE'] != pd.to_datetime('1900-01-01')]
valid_restaurant_list = restaurant_df[['full_name']].drop_duplicates().reset_index(drop=True)

# Add columns for further use
for col in ["place_id", "name", "rating", "review_count", "address",
            "lat", "lon", "types", "opening_hours", "website", "phone", "reviews"]:
    if col not in valid_restaurant_list.columns:
        valid_restaurant_list[col] = None
valid_restaurant_list

,full_name,place_id,name,rating,review_count,address,lat,lon,types,opening_hours,website,phone,reviews
0,D.J. REYNOLDS 351 WEST 57 STREET,None,None,None,None,None,None,None,None,None,None,None,None
1,1 EAST 66TH STREET KITCHEN 1 EAST 66 STREET,None,None,None,None,None,None,None,None,None,None,None,None
2,P & S DELI GROCERY 730 COLUMBUS AVENUE,None,None,None,None,None,None,None,None,None,None,None,None
3,ANGELIKA FILM CENTER 18 WEST HOUSTON STREET,None,None,None,None,None,None,None,None,None,None,None,None
4,CAFE METRO 625 8 AVENUE,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10533,TYPSOON CAFE 947 COLUMBUS AVENUE,None,None,None,None,None,None,None,None,None,None,None,None
10534,DEUX LUXE 384 BROOME STREET,None,None,None,None,None,None,None,None,None,None,None,None
10535,PASTA EATER N GO 744 9 AVENUE,None,None,None,None,None,None,None,None,None,None,None,None
10536,KOL NOODLE 108 WEST 14 STREET,None,None,None,None,None,None,None,None,None,None,None,None
10537,ERA - NEW YORK 589 11 AVENUE,None,None,None,None,None,None,None,None,None,None,None,None

## Step 1: Fetching place info for the top 192 records
This step was halted due to unclear pricing details. To prevent unexpected charges, this method has been suspended for now.

In [ ]:
# # The code below was previously executed, and the resulting data has already been saved to CSV files.
# # To prevent unnecessary re-execution and preserve results, the code has been converted to comments.
# for i, row in valid_restaurant_list.iloc[:192].iterrows():
#     if i % 50 == 0:
#         valid_restaurant_list.to_csv("google_api_restaurant_metadata.csv", index=False)
#         print(f"Checkpoint saved at row {i}")
    
#     if pd.notna(row['place_id']):
#         print(f"Data exists for {row['full_name']}")
#         continue

#     # Step 1: Look up place_id
#     search_url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"
#     search_params = {
#         "input": row['full_name'],
#         "inputtype": "textquery",
#         "fields": "place_id",
#         "key": api_key
#     }

#     try:
#         sres = requests.get(search_url, params=search_params, timeout=5).json()
#         candidates = sres.get("candidates", [])

#         if not candidates:
#             valid_restaurant_list.at[i, "place_id"] = False  # 標記查不到
#             continue

#         place_id = candidates[0]['place_id']
#         valid_restaurant_list.at[i, "place_id"] = place_id

#         # Step 2: Fetch detailed info
#         details_url = "https://maps.googleapis.com/maps/api/place/details/json"
#         details_params = {
#             "place_id": place_id,
#             "fields": {
#                         "name,rating,user_ratings_total,formatted_address,types,geometry,"
#                         "opening_hours,formatted_phone_number,website,reviews,"
#                         "curbside_pickup,delivery,dine_in,editorial_summary,price_level,"
#                         "reservable,serves_beer,serves_breakfast,serves_brunch,serves_dinner,"
#                         "serves_lunch,serves_vegetarian_food,serves_wine,takeout"
#                 },
#             "key": api_key
#         }

#         dres = requests.get(details_url, params=details_params, timeout=5).json()
#         result = dres.get("result", {})

#         valid_restaurant_list.at[i, "name"] = result.get("name")
#         valid_restaurant_list.at[i, "rating"] = result.get("rating")
#         valid_restaurant_list.at[i, "review_count"] = result.get("user_ratings_total")
#         valid_restaurant_list.at[i, "address"] = result.get("formatted_address")
#         valid_restaurant_list.at[i, "lat"] = result.get("geometry", {}).get("location", {}).get("lat")
#         valid_restaurant_list.at[i, "lon"] = result.get("geometry", {}).get("location", {}).get("lng")
#         valid_restaurant_list.at[i, "types"] = ", ".join(result.get("types", []))
#         valid_restaurant_list.at[i, "opening_hours"] = "; ".join(
#             result.get("opening_hours", {}).get("weekday_text", []))
#         valid_restaurant_list.at[i, "website"] = result.get("website")
#         valid_restaurant_list.at[i, "phone"] = result.get("formatted_phone_number")
#         valid_restaurant_list.at[i, "reviews"] = result.get("reviews") or []
#         print(i, place_id, result.get("name"), result.get("rating"), result.get("user_ratings_total"))
#         time.sleep(0.2)

#     except Exception as e:
#         print(f"Error on row {i}: {e}")
#         valid_restaurant_list.at[i, "place_id"] = False

# valid_restaurant_list.to_csv("google_api_restaurant_metadata.csv", index=False)
# print(f"Checkpoint saved at row {i}")

## Step 2: Fetch Popular Time Data for Clustered Restaurants
To retrieve popular time data, the [populartimes](https://github.com/m-wrzr/populartimes?tab=readme-ov-file)] package is used. Given the API request limitations, we prioritize restaurants located in dense clusters (e.g., city center). A total of 672 restaurants were processed in this step.

In [33]:
restaurant_df.columns

Index(['Unnamed: 0', 'CAMIS', 'DBA', 'BUILDING', 'STREET', 'ZIPCODE', 'PHONE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'RECORD DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Community Board', 'Council District', 'Census Tract', 'BIN', 'BBL',
       'NTA', 'inspection_times', 'violation_times', 'full_name'],
      dtype='object')

In [55]:
valid_restaurant_df = restaurant_df[['full_name', 'Latitude', 'Longitude']].drop_duplicates()
valid_restaurant_df['rough_lat'] = np.round(valid_restaurant_df['Latitude'], 2)
valid_restaurant_df['rough_lng'] = np.round(valid_restaurant_df['Longitude'], 2)
# popular area: 40.75, -73.99
valid_restaurant_df.groupby(['rough_lat', 'rough_lng'])['full_name'].count().sort_values(ascending=False)

rough_lat  rough_lng
40.75      -73.99       672
40.76      -73.98       591
           -73.99       544
40.73      -73.99       516
40.75      -73.98       505
                       ...
40.70      -74.02         1
40.84      -73.93         1
40.75      -73.96         1
40.78      -73.94         1
40.77      -74.00         1
Name: full_name, Length: 76, dtype: int64

In [48]:
# # The code below was previously executed, and the resulting data has already been saved to CSV files.
# # To prevent unnecessary re-execution and preserve results, the code has been converted to comments.

# valid_restaurant_list = pd.read_csv('google_api_restaurant_metadata.csv')
# valid_restaurant_list = valid_restaurant_list.merge(valid_restaurant_df, on='full_name')
# valid_restaurant_list['clustered'] = np.where((valid_restaurant_list['rough_lat'] == 40.75) & (valid_restaurant_list['rough_lng'] == -73.99), True, False)

rough_lat  rough_lng
40.75      -73.99       672
40.76      -73.98       591
           -73.99       544
40.73      -73.99       516
40.75      -73.98       505
                       ...
40.70      -74.02         1
40.84      -73.93         1
40.75      -73.96         1
40.78      -73.94         1
40.77      -74.00         1
Name: full_name, Length: 76, dtype: int64

In [50]:
# # The code below was previously executed, and the resulting data has already been saved to CSV files.
# # To prevent unnecessary re-execution and preserve results, the code has been converted to comments.

# Fetch place_id for the clustered restaurant
# for i, row in valid_restaurant_list[valid_restaurant_list['clustered'] == True].iterrows():
#     if pd.notna(row['place_id']):
#         print(f"{row['full_name']} place_id exists: {row['place_id']}")
#         continue

#     place_id = fetch_google_place_id(api_key=api_key,
#                                      place_name=row['full_name'])

#     valid_restaurant_list.at[i, 'place_id'] = place_id
#     print(i, row['full_name'], place_id)
# valid_restaurant_list.to_csv('google_api_restaurant_metadata.csv', index=False)

ANDREW'S NYC DINER 463 7 AVENUE place_id exists: ChIJRdi1GaxZwokR3vmYZ_GDcSM
FIT CAFETERIA (BUILDING A ) 227 WEST   27 STREET place_id exists: False
ARNO RISTORANTE 141 WEST   38 STREET place_id exists: ChIJV0bfnqtZwokRo0b29CRqsS8
HAN BAT RESTAURANT 53 WEST   35 STREET place_id exists: ChIJR751tVNu4oYRGQbCiV0obhs
LAZZARA'S PIZZA CAFE & RESTAURANT 221 WEST   38 STREET place_id exists: ChIJASwLqU9ZwokRAoIgy6k2RgY
245 RICK'S CABARET 50 WEST   33 STREET ChIJ2VhDH6lZwokR_acLQfV63Tc
290 THE TRIPLE CROWN 330 7 AVENUE ChIJDUiwlK9ZwokRgEzA-oCI9a4
348 ZARO'S BREAD BASKET 1 PENNSYLVANIA STATION (AMTRACK) ChIJ30krXK5ZwokRN_iwisXhHxI
392 MUSTANG HARRY'S 352 SEVENTH AVENUE ChIJ6bXru69ZwokRQQ77x79D89M
402 DON PEPI PIZZA 000 PENN STATION ChIJiag-Wq5ZwokRF7-3vlvEWJQ
417 TICK TOCK DINER/ BUTCHER AND THE BANKER 481 8 AVENUE ChIJKUvC6K1ZwokR-6gilCP_YRg
418 TRATTORIA BIANCA 481 8 AVENUE ChIJGwGp6q1ZwokRZAEGF2dtd9c
435 WAKAMBA 543 8 AVENUE ChIJl60eBK1ZwokReIc25YcPsTA
443 STARBUCKS 370 7 AVENUE ChIJpU_RVK5ZwokRmAtTNwJNDyQ
484 NEW YORKER HOTEL KITCHEN 481 8 AVENUE ChIJKxW9qbVZwokRdp--o2I-RTE
493 STARBUCKS 462 7 AVENUE ChIJY7SYAqxZwokRwEv7sazo7k0
541 STARBUCKS 261 5 AVENUE ChIJwf0fO6ZZwokR3gpyFtEjm5Q
546 NOSH! - COURTYARD BY MARRIOTT 114 WEST   40 STREET ChIJo4xy46pZwokRJbPmZ5BUBS4
578 STARBUCKS 494 8 AVENUE ChIJe0vUxq1ZwokR2U9PaJyn9Mk
621 PLAYWRIGHT IRISH PUB 27 WEST   35 STREET ChIJed_amqlZwokRZ2QQm75dbaI
651 ZARO'S FAMILY BAKERY 2 PENN PLAZA ChIJ30krXK5ZwokRN_iwisXhHxI
738 HYO DONG GAK 51 WEST   35 STREET ChIJ732mealZwokRofYjjral1pY
823 JACK DEMSEY'S PUB 36 WEST   33 STREET ChIJW3PAHalZwokRrw41djg_Tik
837 NICK & STEF'S STEAKHOUSE 9 PENN PLAZA ChIJ25nNcq5ZwokRRLkSWz8jL3U
897 PENN CAFE & EATERY 0 PENN STATION ChIJP_D1PehZwokRoVmwpUvw-ek
900 CHIPOTLE MEXICAN GRILL 304 WEST   34 STREET ChIJDy4b5q1ZwokR7Ayp1Ap3-c0
946 SHAMAS DELI 150 WEST   38 STREET ChIJIUlcg6tZwokR13Y0_Y86cEw
947 SWAGAT INDIAN RESTAURANT 205 WEST   29 STREET ChIJ3_s_v69ZwokRJldq7sPweF0
994 PRIMO CAPPUCCINO 0 PENN STATION ChIJhZJ3Yq5ZwokRxB-xpb0ZHyQ
1007 CAFE NUNEZ 240 WEST   35 STREET ChIJkZRgM6xZwokRNp1lrJM2hL8
1032 STITCH BAR 247 WEST   37 STREET ChIJtcPJYqtZwokRiiFBAJz8krQ
1051 STOUT 133 WEST   33 STREET ChIJJ91wx65ZwokRnjW2e69Imic
1059 STARBUCKS 875 6 AVENUE ChIJFY4KLq9ZwokROL0kzgBIbgE
1062 HELEN MILLS EVENT SPACE AND THEATER 135 WEST   26 STREET ChIJs0qsbKVZwokRe2DY_TOAnjg
1094 CHIPOTLE MEXICAN GRILL 283 7 AVENUE ChIJj7T4TqVZwokRjFWjHrX9ff0
1177 POCHA 32 15 WEST   32 STREET ChIJJdmP46hZwokRqffbVAebL6s
1241 DUNKIN 152 WEST   31 STREET ChIJLW-vAa9ZwokRxF6TNljN9fY
1314 FEILE 133 WEST   33 STREET ChIJ8587uK5ZwokRhBVe6xxdXrw
1315 AYZA CAFE & WINE BAR 11 WEST   31 STREET ChIJNw7LkqhZwokRnBhQLw_RyFM
1339 DUNKIN' DONUTS 265 WEST   37 STREET ChIJwfNx_6xZwokRJiocgea0kDc
1355 STARBUCKS COFFEE 315 7 AVENUE ChIJX4lqiq9ZwokRyI0fufmrJLI
1360 WOORIJIP 12 WEST   32 STREET ChIJzfG-8ahZwokR5FLB4KmxBXI
1448 AMERICA GOURMET FOOD 831 6 AVENUE ChIJieVlZ69ZwokRXfKrKftI0lI
1506 FASHION INSTITUTE OF TECHNOLOGY DAVID DUBINSKY STUDENT CENTER 227 WEST   27 STREET ChIJ6wb1E7BZwokRkegC09syV9Y
1507 GAGOPA KARAOKE 28 WEST   32 STREET ChIJQYq46KhZwokRPyXGganv1Vw
1509 The Rutherord 1 PENN PLAZA ChIJ_SRPqI1ZwokRcBVTMGsnBLE
1521 DUNKIN', BASKIN ROBBINS 302 5 AVENUE ChIJP0iOi6hZwokRz5OCQqnqZsc
1553 LEGENDS NYC 6 WEST   33 STREET ChIJV8smVahZwokRodosOEyb7IU
1558 B AND B RESTAURANT 165 WEST   26 STREET ChIJ9WbzQ6VZwokRJ_qUroHyl6Y
1597 KARAOKE WOW 10 WEST   32 STREET ChIJ40B08ahZwokRKPCDKFpkj7E
1632 CHELTON'S BAR & GRILLE (DOUBLETREE BY HILTON) 128 WEST   29 STREET ChIJ1-macK9ZwokRQAbWUXznXjA
1675 STARBUCKS 227 WEST   27 STREET False
1681 FRESH & CO 363 7 AVENUE ChIJm5XlqK9ZwokRskEZP6W-24c
1688 Avenida 1 PENN PLAZA ChIJhZJ3Yq5ZwokR7_5fevZJH8E
1699 CHIPOTLE MEXICAN GRILL 501 7 AVENUE ChIJj7T4TqVZwokRjFWjHrX9ff0
1700 K TOWN POHCA 34 WEST   32 STREET ChIJ35vTJk1ZwokRPHdJAKnM1jw
1716 PIG 'N' WHISTLE 202 WEST   36 STREET ChIJb3gra6xZwokRRfr2bL2AfhI
1751 HAMPTON INN-HERALD SQUARE 116 WEST   31 STREET ChIJuyEmPa9ZwokRE0zkFnH6YDk
1756 HOLIDAY INN EXPRESS - MANHATTAN 232 WEST   29 STREET ChIJXzk5v6hZwokR6aBXNc1gjQU
1759 RESIDENCE INN TIMES                                                                           SQUARE 1033 6 AVENUE ChIJUyVsVKpZwokRwyknPdvbprs
1780 NEW WONJO RESTAURANT 23 WEST   32 STREET ChIJLc5V-6hZwokRCO-MIGUc9wA
1819 MISS KOREA 10 WEST   32 STREET ChIJ99_m8KhZwokRz33z_j0NaQ8
1842 FIVE GUYS FAMOUS BURGERS AND FRIES 316 WEST   34 STREET ChIJHRQr8a1ZwokR0ZUDrOkxKgU
1850 PARIS BAGUETTE 6 WEST   32 STREET ChIJA34-5ahZwokRumNK9CKW-uk
1887 KRISPY KREME 2 PENN PLAZA ChIJiag-Wq5ZwokR9x2Wlf7j7dc
1918 DUNKIN/JIMMY JOHN'S 316 WEST   34 STREET ChIJrwdddgdZwokRtY2t1KbAftc
1970 CHICKPEA 0 PENN STATION ChIJy8W8261ZwokRFroXdrT-2D0
1996 SALT AND PEPPER RESTAURANT & CAFE 139 WEST   33 STREET ChIJdSmjwK5ZwokRNCLrd6C3gJ0
2045 STUMPTOWN COFFEE 18 WEST   29 STREET ChIJT2h1HKZZwokR0kgzEtsa03k
2059 AJISEN RAMEN 136 WEST   28 STREET ChIJ7_DNgK9ZwokR-35SiqUmnfs
2090 THE SPOT KARAOKE LOUNGE 34 WEST   32 STREET ChIJw8CO56hZwokRvWRVW6h17FA
2097 FIVE GUYS FAMOUS BURGERS AND FRIES 343 7 AVENUE ChIJX1Rtva9ZwokRutZ91mSY71Y
2160 MANHATTAN CENTER / HAMMERSTEIN BALLROOM 311 WEST   34 STREET ChIJXzVc8a1ZwokRMxYbuMX3F7g
2174 STARBUCKS 977 AVENUE OF THE AMERICAS ChIJ-WebneFZwokR2MXIQKU90Ew
2219 DUNKIN'/HUDSON NEWS 2 PENNSYLVANIA PLAZA ChIJjyhussVZwokRaDyqPpcleDM
2220 DUNKIN 2 PENNSYLVANIA PLAZA ChIJjyhussVZwokRaDyqPpcleDM
2221 DUNKIN',' HUDSON NEWS 2 PENNSYLVANIA PLAZA ChIJjyhussVZwokRaDyqPpcleDM
2228 THE LIBERTY 29 WEST   35 STREET ChIJxVtTJfxYwokRqFWUb2-nUZU
2272 MARU 11 WEST   32 STREET ChIJT1oW08erQjQRD1dVyNQjPbQ
2275 SBARRO 159 WEST   33 STREET ChIJmymFlK5ZwokRa6xjH2fPP4s
2281 DUNKIN 1369 BROADWAY ChIJg2KO7WVZwokRYFaAQKEGHtU
2290 HAMPTON INN EMPIRE STATE BUILDING 59 WEST   35 STREET ChIJj3HneqlZwokRSLaBk4rvMcw
2320 JACK DOYLES PUB & RESTAURANT 240 WEST   35 STREET ChIJ0RAxza1ZwokRaCu1WooWYVI
2341 RAMINI ESPRESSO BAR 265 WEST   37 STREET ChIJico0-axZwokRPeqC2TdsOKI
2348 GAONNURI 1250 BROADWAY ChIJ_xUY2qhZwokRDDqPeRtPQJM
2352 GINSENG MUSEUM CAFE 315 5 AVENUE ChIJHdzvXKhZwokRz-ofTXGcsSM
2382 THE KEG ROOM 53 WEST   36 STREET ChIJ8e_e1KtZwokRG1khy16JxDo
2384 PIONEERS BAR & LOUNGE 134 WEST   29 STREET ChIJkTptdq9ZwokR9CCc1A4ZcNw
2386 PENNSYLVANIA 6 132 WEST   31 STREET ChIJM8GuI69ZwokR3BbXDomZSAA
2406 SHANGHAI BROADWAY RESTAURANT 150 WEST   36 STREET ChIJhXJGCKxZwokRuKkLd9ObmoA
2424 FAIRFIELD INN CHELSEA 116 WEST   28 STREET ChIJgXlbh6VZwokRbhvJi3Dvi2o
2426 STELLA 34 151 WEST   34 STREET ChIJ98yXUKlZwokRdb3AjM-Y0zo
2432 VICTORY RESTAURANT & LOUNGE 221 WEST   38 STREET ChIJawE1P2RZwokRRCBYnzLZw2s
2451 MUI KITCHEN & BAR 10 WEST   32 STREET ChIJiZ0a8ahZwokRz-h_V_R8fEI
2468 BCD TOFU HOUSE 5 WEST   32 STREET ChIJ3fZz-6hZwokRvjeitvq-5fY
2529 AMC THEATRES 312 WEST   34 STREET ChIJd0z48K1ZwokR38rt39Sh3Hc
2548 OOTOYA 141 WEST   41 STREET ChIJOYze16pZwokRG9GTU_NvhGM
2559 MEW 53 WEST   35 STREET ChIJh_4leqlZwokRJxjh98xRrd4
2565 GRACE STREET 17 WEST   32 STREET ChIJ9Sto4ahZwokRXpWiQYiOOOo
2594 MONARCH 960 6 AVENUE False
2620 STARBUCKS 151 WEST   34 STREET False
2628 MISS KOREA BARBECUE "SUN" 10 WEST   32 STREET ChIJ99_m8KhZwokRz33z_j0NaQ8
2648 PARIS BAGUETTE 567 7 AVENUE ChIJv_FoR6tZwokRAispQ1mGkaE
2661 THE SKYLARK 530 FASHION AVENUE ChIJtcPJYqtZwokRiiFBAJz8krQ
2683 WASABI SUSHI BENTO 561 SEVENTH AVENUE ChIJJ8EkR6tZwokR8XihRuI6yW4
2698 PERGOLA 36 36 WEST   28 STREET ChIJS-435aVZwokRCKIL4x3naMw
2699 OCABANON 245 WEST   29 STREET ChIJnYSJ169ZwokRiH0bzxxTYWM
2722 AMERICAN WHISKEY 247 WEST   30 STREET ChIJf6-s0q9ZwokRddxGZsSVODw
2730 VIVID CABARET 61 WEST   37 STREET ChIJfUHlNKpZwokRPAjzNpKuxWo
2744 SOJU HAUS 315 5 AVENUE ChIJwTK_XahZwokRghFqibPmuKQ
2755 DISTRICT TAP HOUSE 246 WEST   38 STREET ChIJLYCZ9KxZwokRzPV1ej20A78
2756 SWEETS LABORATORY BY HANAMIZUKI 143 WEST   29 STREET ChIJK-6i_ClZwokR1JpZN9dZgCI
2774 GRACE CAFE 572 8 AVENUE ChIJtfs44axZwokRPfNIDc4aGSk
2796 KUSHI KUSHI YAKI 2 WEST   32 STREET ChIJh6uc4PdZwokRqq2GphaHzws
2814 WAFELS & DINGES 102 WEST   35 STREET ChIJm8cpXKlZwokRmEMsUOnHrnI
2833 DUNKIN 10 WEST   33 STREET ChIJxbL-VKhZwokRFiaBz7Lrpg8
2857 JOHN SULLIVAN'S PUB 210 WEST   35 STREET ChIJMUiKI6xZwokRDEokmGYpJK8
2897 MEXICUE 1440 BROADWAY ChIJK6ywGKtZwokRLFWYCXL5J3k
2903 BLACK IRON BURGER 245 WEST   38 STREET ChIJnSnH8qxZwokRzoMUSAeaFAA
2922 KRUSH 2 WEST   32 STREET ChIJGT0h9KhZwokRBR4S7oqJOoU
2935 THE HAROLD 1271 BROADWAY ChIJ_yWc1qhZwokRTxGO4AD3FJ0
2937 AL'S DELI 458 7 AVENUE ChIJq5Y3IqxZwokRkzI2auAoqg8
2938 SPACE BILLARD 34 WEST   32 STREET ChIJz_3Q3qhZwokRAX09MCwhWTc
2963 7 GRAMS CAFFE 275 7 AVENUE ChIJqXTjSaVZwokREUBBnhV2hbI
2967 JONGRO BBQ 22 WEST   32 STREET ChIJQ3Jl76hZwokRnS1-MQHYhZE
2974 CLOUD SOCIAL 6 WEST   32 STREET ChIJm7c18ahZwokRyiqSr6I75d0
3007 CAFE GRUMPY 200 WEST   39 STREET ChIJmzE1Y6tZwokRQLY6pr6tTDk
3022 RIB N0.7 32 WEST   33 STREET ChIJ8xkVcsNZwokRtMSU4fiXJdg
3026 CULTURE 36 247 WEST   36 STREET ChIJdTyxUaxZwokRNAyNj1mBu8A
3031 BONCHON 325 5 AVENUE ChIJQzFkRahZwokRxMJjMYIbmow
3034 JUST SALAD 151 WEST   34 STREET ChIJ85jzU6lZwokRJnAc-T8TmiM
3049 COURTYARD BY MARRIOTT MANHATTAN CHELSEA 135 WEST   30 STREET ChIJFQEgD69ZwokR3_UUCqb0gTg
3055 THE KUNJIP 32 WEST   32 STREET ChIJdQxV-KhZwokRsyAt1XYvtiQ
3078 RON BEN-ISRAEL CAKES 247 WEST   38 STREET ChIJEbd26otZwokRdO61wmGbbVw
3107 JUNIPER 237 WEST   35 STREET ChIJ5Z-4NaxZwokRF98-wGsCVDM
3131 GONG CHA 12 WEST   32 STREET ChIJzfG-8ahZwokR0JSegXVEBCk
3144 CROMPTON ALE HOUSE 159 WEST   26 STREET ChIJY2mhaaVZwokREl-Qs_zLY_Y
3158 COSTAS 30 WEST   35 STREET ChIJw2YhnKlZwokRj1VGGHWoZzc
3201 SOCIAL CIRCLE at CAMBRIA HOTELS & SUITES NEW YORK-CHELSEA 123 WEST   28 STREET ChIJ27alQQBZwokR4B73wKiALog
3226 BREAD & BUTTER 303 5 AVENUE ChIJRZJpYahZwokREPSRleELmCs
3260 DUNKIN 153 WEST   36 STREET ChIJE3tB9atZwokRbvUHN1V3RD0
3274 SID GOLD'S REQUEST ROOM 165 WEST   26 STREET ChIJz_NwRKVZwokRGp7XDpwqNnI
3299 HAYMAKER BAR & KITCHEN 252 WEST   29 STREET ChIJ8bLkJLBZwokRYVmAyFdpJIc
3325 GAMMEEOK 9 WEST   32 STREET ChIJmVfI-ahZwokRZdv0oaUCRKk
3359 MARKET CRATES 26 WEST   33 STREET ChIJ69XqAqlZwokRlSebQJigZ7E
3419 CORK & KALE AT EVEN HOTEL 321 WEST   35 STREET False
3439 THEATER (FLY) 4 PENN PLZ False
3442 BT4 AISLE B 4 PENN PLZ False
3443 GOLD BAR A BT5 4 PENN PLZ False
3444 GOLD BAR B BT6 4 PENN PLZ False
3445 CHASE LOUNGE - 3rd Floor 4 PENN PLZ False
3447 LEGEND'S ROOM - OA3070 4 PENN PLZ ChIJY8WS-3umzokRpjbh9DppPA8
3448 BT3 AISLE A 4 PENN PLZ False
3449 HOT DOG CONCESSION 4 PENN PLZ False
3452 BAR GARDEN 4 PENN PLZ False
3453 BAR - (BD6130) 4 PENN PLZ False
3454 GARDEN MARKET 4 PENN PLZ ChIJV322o9C7zokRua1nP4VDEGo
3455 BAR AT THE GARDEN 4 PENN PLZ ChIJpdSDcq5ZwokRazrue5ZXJ4I
3456 HAMBURGER, DAILY BURGER 4 PENN PLZ ChIJEQSGba5ZwokR2INTZLf4y9A
3457 CHICKEN, FRIES CONCESSION 4 PENN PLZ ChIJj7BaZAJdwokR7dykMJ_-KqQ
3458 GARDEN PUB 4 PENN PLZ ChIJY8WS-3umzokR8vyYBOXlZ1o
3459 CARNAGIE DELI - FB8150 4 PENN PLZ ChIJ0QfXba5ZwokRrWRtB1LQNps
3460 PIZZA CONCESSION 4 PENN PLZ False
3461 THE SHACK - CB8030 (CB8040) 4 PENN PLZ False
3462 HOT DOG CONCESSION 4 PENN PLAZA ChIJ63UOFa5ZwokR195FnTIXPcc
3463 Bar at the Garden 4 PENN PLZ ChIJpdSDcq5ZwokRazrue5ZXJ4I
3464 CHICKEN & FRIES 4 PENN PLZ ChIJJYdc65iozokR_63CFyOK-eA
3465 MIGHTY QUINN'S BBQ - FA8032 (CA8033) 4 PENN PLZ False
3466 GARDEN MARKET EXPRESS - FA8150 4 PENN PLZ False
3467 Daily Burger 4 PENN PLZ ChIJEQSGba5ZwokR2INTZLf4y9A
3468 BAR 4 PENN PLZ False
3469 GARDEN MARKET HOT DOG CONCESSION 4 PENN PLZ False
3470 CASA NONNA PIZZA CONCESSION 4 PENN PLZ ChIJ-_lNIdj9xokR1X4dcV9p3jU
3471 BEER PUB (BRIDGE PUB) 4 PENN PLZ ChIJ5XrvGa5ZwokRVFbhYo--qW8
3473 HOT DOG CONCESSION, GARDEN MARKET 4 PENN PLZ False
3474 GARDEN MARKET – HOT DOG CONCESSION (FA6050) 4 PENN PLZ False
3479 FUKU - FA6090 4 PENN PLZ False
3480 BAR AT THE GARDEN (BA6110) 4 PENN PLZ ChIJY8WS-3umzokR8vyYBOXlZ1o
3481 TAO SUSHI CONCESSION/FRATELLI 4 PENN PLZ False
3486 HAMBURGER, CELEBRITY CHEF, SIMPLY VEGAN FB6030 (CB6035) 4 PENN PLZ False
3487 GARDEN MARKET, DUNKIN 4 PENN PLZ ChIJ4VVf_LJZwokRJenYZQ6SvGQ
3488 MIKE'S HOT HONEY - FB6060 4 PENN PLZ False
3489 PAULIE GEE'Z 4 PENN PLZ ChIJbT-CamfHxokRelazxwDHHZg
3491 GLUTEN FREE AT THE GARDEN/TOP DOG/HOT DOG CONCESSIONS - FB6140 (CB6142) 4 PENN PLZ False
3492 JEAN-GEORGES SIMPLY TACOS, TASTY NACHO BAR 4 PENN PLZ False
3493 FARLEY'S BAR 4 PENN PLZ ChIJBZ9wGa5ZwokR56eDoKA1vOo
3498 GARDEN MELT 4 PENN PLZ False
3508 EVENT LEVEL CLUB (DELTA SKY 360 BAR) BA5075 4 PENN PLZ False
3509 HANAMICHI 28 WEST   32 STREET ChIJQYq46KhZwokR9GuyY4w2EYI
3510 BAR - (BA6020) 4 PENN PLZ False
3511 RAFTERS/PRIME RIB - FC6130 (CC6132) 4 PENN PLAZA False
3512 SUITE 200, 1879 4 PENN PLZ False
3513 KOBEYAKI/HAMBURGER CELEBRITY CHEF - FD6010 4 PENN PLZ ChIJlaUCHbxZwokRUPWZkyNQyYg
3514 MIGHTY QUINN'S BBQ/CARNEGIE DELI CONCESSIONS 4 PENN PLAZA ChIJnRjKm6tZwokRge1J396OZig
3515 BAR (GARDEN BAR 6TH FLOOR) 4 PENN PLAZA ChIJpdSDcq5ZwokRazrue5ZXJ4I
3517 PRESS ROOM 4 PENN PLZ False
3518 HOT DOG CONCESSION (FC6100) 4 PENN PLZ False
3519 THE PRIME RIB, DUNKIN DONUTS - FA8040 (CA8041) 4 PENN PLZ False
3520 EMPLOYEE FEEDING 4 PENN PLZ False
3521 MADISON CLUB 4 PENN PLZ ChIJQQoTrO3eNIgRhFceIy_ggD0
3527 THE BREAD FACTORY CAFE 470 7 AVENUE ChIJa_jYFaxZwokR5xYlplIL3DY
3528 MAIN NOODLE HOUSE 1011 6 AVENUE ChIJU1cPR2FZwokR9w8VUXER1gc
3533 ROWLAND'S BAR AND GRILL 151 WEST   34 STREET ChIJNYLWpq5ZwokRXoq87mR3j5U
3539 MCDONALD'S 809 6 AVENUE ChIJz7g82KtZwokRsXU0FMeLpmU
3558 STARBUCKS COFFEE # 26528 1040 6 AVENUE ChIJy6py96pZwokRUwo8M9BbVtU
3586 GREGORYS COFFEE 520 8 AVENUE ChIJZwFsq61ZwokRCquELy8Q3Gw
3600 DUNKIN',' BASKIN ROBBINS 289 7 AVENUE ChIJP97DV7NZwokRftf2tZbvjzI
3607 THE GASTRO BAR 345 WEST   35 STREET ChIJ9UFEiK1ZwokRHhIZbZT8Afk
3615 SHANGHAI MONG 30 WEST   32 STREET ChIJsRRm3qhZwokRQDPFy0HJx7s
3629 LENWICH 202 WEST   40 STREET ChIJzbjWXqtZwokRJ08VQTsz7KA
3631 THE PICNIC BASKET 65 WEST   37 STREET ChIJ2bKsNKpZwokRZyTuwt_YAqA
3638 DUNKIN 155 WEST   35 STREET ChIJOxYiBKxZwokRaKwbA5O54QQ
3639 VERSA 218 WEST   35 STREET ChIJS_9NWCFZwokR5CWRh_2zm7I
3640 Thread Lobby Bar 218 WEST   35 STREET ChIJD4pwJaxZwokR0qqTEwVPsB0
3643 LIBERTY BAGEL MIDTOWN 260 WEST   35 STREET ChIJEWqQDLJZwokR8K5wVBL9n6g
3647 BALADE EASTERN MEDITERRANEAN 144 WEST   37 STREET ChIJ5aNJiqtZwokR-cKUOOjAAEw
3649 KARAOKE CITY 22 WEST   32 STREET ChIJO_QT76hZwokRFp_9y5N6RQY
3651 L'AMICO, BACK BAR 839 6 AVENUE ChIJqyVsRq9ZwokRukmFQg8jzvg
3666 TOUS LES JOURS 31 WEST   32 STREET ChIJr5cB5KhZwokR9YCDPDiliFo
3679 TRADEMARK 38 WEST   36 STREET ChIJCYWVhqlZwokRe3CEB0PChBI
3683 SHAKE SHACK 1333 BROADWAY ChIJP-1S5KtZwokRM2NwZm2b3ec
3696 BARN JOO 35 34 WEST   35 STREET ChIJfzDanalZwokReBUChuK5tmI
3716 Sorimmara 2 WEST   32 STREET ChIJC-GfTABZwokRT4j4uF-16nE
3717 CHOP'T 1450 BROADWAY ChIJI4ghKatZwokRe6WONA8H0kM
3720 BARNEY BROWN 822 AVENUE OF THE AMERICAS ChIJC0oNnadZwokRCcxdRYjPT_0
3727 LADY M CONFECTIONS 1178 BROADWAY ChIJ4dOzCKZZwokRTDZm4yrHq7E
3733 PANDA EXPRESS 414 8 AVENUE ChIJNzfuJ65ZwokREXfAYA37Hyk
3736 THE MAZE 32 WEST   32 STREET ChIJNR5n6KhZwokRXwivwaPBl7A
3738 JUST SALAD 291 7 AVENUE ChIJk2UeW6VZwokRJn19BaYEu84
3774 OSAMIL 5 WEST   31 STREET ChIJjzU486hZwokRR1xdL_9PWPU
3787 BRAVO PIZZA 360 7 AVENUE ChIJ_050uq9ZwokRMGsTwRIZMpQ
3794 LA COLOMBE 7 BRYANT PARK ChIJ3Xrz-apZwokRlXC_woD9axg
3817 HEALTHY CHOICE GOURMET DELI & PIZZA 341 7 AVENUE ChIJV7s_va9ZwokRE8ftZ5t2YVA
3819 GREGORY'S COFFEE 874 AVENUE OF THE AMERICAS ChIJQTNrM69ZwokR3ggxzgeelqQ
3825 HOMEWOOD SUITES BY HILTON NEW YORK MIDTOWN MANHATTAN TIMES SQUARE 312 WEST   37 STREET ChIJ_6umC61ZwokRUfAD4mkkMIs
3845 BURGER KING, CINNABON 1313 BROADWAY ChIJnT6gRalZwokR6yeU__dE_3Y
3860 HOOPS CABARET AND SPORTS BAR 48 WEST   33 STREET ChIJuSs_H6lZwokRyyL7pldfp1M
3867 MCDONALD'S 490 8 AVENUE ChIJfzHhupZZwokRB7lFLdaT8sk
3870 NON SOLO PIADA 302 WEST   37 STREET ChIJAVfFB61ZwokRqUkChslCdP4
3873 TURNTABLE LP BAR 34 WEST   32 STREET ChIJYwp16KhZwokRRQcdgVU4C5w
3907 BB.Q CHICKEN 25 WEST   32 STREET ChIJFcNg46hZwokROlvbElpUw5o
3915 ESSEN 519 8 AVENUE ChIJ8YvJvK1ZwokRIvJ1IXpRM8s
3917 MY COOKING PARTY 130 WEST   29 STREET ChIJbSHDjq1ZwokRZ_aroG2KaK0
3956 TIR NA NOG 254 WEST   31 STREET ChIJoxV2461ZwokRqS4g6NxmLo4
3967 KAZUNORI 15 WEST   28 STREET ChIJsaYZEKZZwokRThIP62r39zQ
3969 AMAZON NYC 7 WEST   34 STREET ChIJHeV96EhZwokRSp3V_SAopuw
4003 CULTURE 307 307 WEST   38 STREET ChIJi7UFIq1ZwokRRlDLoi1RxRY
4020 THE SHOP + 63 WEST   35 STREET ChIJYcKPfKlZwokRUBoMY_KHf5s
4022 HOTEL STANFORD 43 WEST   32 STREET ChIJoS_d36hZwokRtJmqzJNEsrs
4038 FLIK @ HOLY NAME PROVINCE 129 WEST   31 STREET ChIJCTKiHq9ZwokR8iBJtG6i2DI
4055 HOLIDAY INN EXPRESS MANHATTAN TIMES SQUARE SOUTH 60 WEST   36 STREET ChIJNz28f6lZwokRG7XqHzfM0Us
4067 APERIBAR 120 WEST   41 STREET ChIJZTInQIhZwokR8GBPDoHJMok
4076 HYATT HOUSE NEW YORK, CHELSEA 815 AVENUE OF THE AMERICAS ChIJG9sDiqVZwokRgMN1mn5kEa0
4093 TURNTABLE CHICKEN JAZZ 20 WEST   33 STREET ChIJWWFYX6hZwokRiVPlneRsibg
4099 ABIKO CURRY 2 WEST   32 STREET ChIJG3Qn9KhZwokR7Lkh83C3QSw
4102 VARIETY COFFEE ROASTERS 261 7 AVENUE ChIJ49KnM6VZwokRArJkBByO0Dc
4118 DELGADO'S CANDY STORE 1407 BROADWAY LOBBY ChIJ_8GQGK1ZwokRlqcTVWbFyQ4
4121 MARKET CRATES 224 WEST   35 STREET ChIJbRPdL6xZwokRKyItEiAgbz4
4142 ITAEWON POCHA 28 WEST   32 STREET ChIJX3vA5ahZwokRd9ZnszaGXFM
4146 BEYOND SUSHI 134 WEST   37 STREET ChIJPy94jKtZwokRRODqoL09Acw
4150 JUICE GENERATION 1407 BROADWAY ChIJK_2ndatZwokRpVHzq8DSvao
4175 STARBUCKS COFFEE 1411 BROADWAY ChIJRX23FatZwokRSA4n7tp75Tw
4219 & PIZZA 15 WEST   28 STREET ChIJsaYZEKZZwokRxICmrKSu8Pw
4224 POKE BAR 1333 BROADWAY ChIJ-zOk_KtZwokRhwdR3sRlwMQ
4241 MIGHTY QUINN'S BBQ 1407 BROADWAY ChIJnRjKm6tZwokRge1J396OZig
4272 JOE'S PIZZA 1435 BROADWAY ChIJifIePKtZwokRVZ-UdRGkZzs
4273 VOCO AN IHG HOTEL 341 WEST   36 STREET ChIJl64LeK1ZwokR7u2JvudWqgM
4276 BLUESTONE LANE 1375 BROADWAY ChIJ_0SkkKtZwokRZlbtIC9fYMg
4305 SUBWAY 1400 BROADWAY ChIJmVVCaKJZwokRDaHvwWp3lPw
4317 LUKE'S LOBSTER 1407 BROADWAY ChIJK_2ndatZwokRCrb7IrJ5810
4358 COOK EATERY 1412 BROADWAY ChIJuwEPBatZwokRjUonZ0lY6Bs
4367 TASTE KITCHEN 316 WEST   36 STREET ChIJEajIma1ZwokRc8lX7ZfCnZQ
4370 MAGIC HOUR 485 7 AVENUE ChIJl5pBc6xZwokRZrnK_FqSNJI
4371 LEGASEA ,  BAR MOXY 485 7 AVENUE ChIJl5pBc6xZwokRyba8gBQv0F8
4380 FIVE SENSES 9 WEST   32 STREET ChIJ1dPu-KhZwokR-bL1w45w0vY
4387 CORVO COFFEE 270 WEST   39 STREET ChIJl0a-w6xZwokRPUVS8vxIgYI
4400 KING'S STREET COFFEE 121 WEST   30 STREET ChIJV90jFK9ZwokR4G-WwPhjlsc
4421 THE RAG TRADER, BOPEEP BAR 70 WEST   36 STREET ChIJFWsPfqlZwokRRfCNgutT9pU
4429 SWEETGREEN 1384 BROADWAY ChIJqfjlvKtZwokRjV2vOk_hyEE
4459 DIG INN 133 WEST   38 STREET ChIJFW6qqRtZwokRoRl38oJxFEM
4476 MISSION NYC 229 WEST   28 STREET ChIJs-E1jKlZwokR5hN4X81BDuU
4506 LET'S MEAT 307 5 AVENUE ChIJJ4y_XahZwokRgO8olYwA7Cg
4519 FIVE GUYS FAMOUS BURGERS AND FRIES 1008 6 AVENUE ChIJk0y1SqpZwokR7BJIt2nqkwo
4534 ICHIRAN 132 WEST   31 STREET ChIJAduJGa9ZwokR5p0GowLG9P8
4536 ANTOYA 37 WEST   32 STREET ChIJAQAE4ahZwokRhGsJIi1HqYU
4542 GOPCHANG STORY NY 312 5 AVENUE ChIJ-SmG9ahZwokRLbN33Zvknig
4575 KEKI MODERN CAKES 315 5 AVENUE ChIJX9_OQqhZwokRuD3fUB8btJ4
4582 TURNTABLE CHICKEN & ROCK 290 5 AVENUE ChIJrzvTtbpZwokR5DGCV14D0tQ
4595 OUR VODKA 151 WEST   26 STREET ChIJCcQxrjZZwokRozZ82EU38tA
4604 BRASSERIE TOAST CAFE 968 AVENUE OF THE AMERICAS ChIJAQCkYqlZwokRIf2lYzUIKV8
4621 MUSES 35 BAR & KARAOKE 248 WEST   35 STREET ChIJUYpxy61ZwokRP5qdHou1WrE
4648 THE TAILOR PUBLIC HOUSE 505 8 AVENUE ChIJ76gDrpxYwokRYpcajBXjfZY
4662 L'ADRESSE AMERICAN BISTRO 5 Bryant Park ChIJHWSG5qpZwokR5ByrYZRCsaI
4750 ELSIE ROOFTOP 1412 BROADWAY ChIJ0Q7xqoBZwokRkrPoL2Es1X0
4795 DUNKIN 1235 BROADWAY ChIJ54MwE65ZwokRG20jhVMjcng
4826 HORTUS NYC 271 5 AVENUE ChIJyX-WBOZZwokRROjVTDdgeZE
4828 MAMA 11 WEST   32 STREET ChIJa2YT-ahZwokR-FABvLXcKi0
4829 HANOK KOREA HOUSE 11 WEST   32 STREET ChIJ71Ny-ahZwokRyLBkv34bYRg
4830 GOCHUJANG 11 WEST   32 STREET ChIJa2YT-ahZwokR-FABvLXcKi0
4831 ROLL & KATSU KITCHEN 11 WEST   32 STREET ChIJiYcVzRJZwokRfw8qFE8eJq0
4832 KOBEQUE 11 WEST   32 STREET ChIJnY5y-ahZwokR25gZ9fmPP8A
4833 KUNG FU TEA 11 WEST   32 STREET ChIJKXiD-ahZwokRTuzm04INKmo
4834 JIAN BING MAN 11 WEST   32 STREET ChIJe2YT-ahZwokR2ZbMTdl9VeM

In [105]:
# # The code below was previously executed.
# # To prevent unnecessary re-execution and preserve results, the code has been converted to comments.

# valid_restaurant_list = pd.read_csv('google_api_restaurant_metadata.csv')
# valid_restaurant_list['time_spent_min'] = None
# valid_restaurant_list['time_spent_max'] = None
# valid_restaurant_list['popular_data'] = False

In [119]:
updated_popularity_rows = []
restaurant_metadata = pd.read_csv('google_api_restaurant_metadata_step2.csv')
restaurant_popular_time = pd.read_csv('google_api_restaurant_popular_time_step2.csv')

cond1 = (restaurant_metadata['clustered'] == True)
cond2 = (restaurant_metadata['place_id'].str.len() > 10)

# Todo: Remove .head(10) and fetch the remaining records 
for i, row in restaurant_metadata[cond1 & cond2].head(10).iterrows():
    place_id = row['place_id']
    
    if row.get('popular_data') is True:
        print(f"{row['place_id']} has been processed")
        continue

    try:
        response = populartimes.get_id(api_key=api_key, place_id=place_id)
        place_info_df, popularity_df = gen_place_info_popularity_df(response)

        for col in place_info_df.columns:
            restaurant_metadata.at[i, col] = place_info_df.at[0, col]
        
        restaurant_metadata.at[i, 'popular_data'] = True

        updated_popularity_rows.append(popularity_df)
        print(f"{i}, {row['place_id']} successfully fetched!")

    except Exception as e:
        print(f"❌ Failed at row {i} (place_id={place_id}): {e}")
        continue

restaurant_metadata.to_csv('google_api_restaurant_metadata_step2.csv', index=False)
final_popularity_df = pd.concat(updated_popularity_rows, ignore_index=True)
restaurant_popular_time = pd.concat([restaurant_popular_time, final_popularity_df], ignore_index=True)
restaurant_popular_time.to_csv('google_api_restaurant_popular_time_step2.csv', index=False)

ChIJRdi1GaxZwokR3vmYZ_GDcSM has been processed
ChIJV0bfnqtZwokRo0b29CRqsS8 has been processed
ChIJR751tVNu4oYRGQbCiV0obhs has been processed
175, ChIJASwLqU9ZwokRAoIgy6k2RgY successfully fetched!
245, ChIJ2VhDH6lZwokR_acLQfV63Tc successfully fetched!
290, ChIJDUiwlK9ZwokRgEzA-oCI9a4 successfully fetched!
348, ChIJ30krXK5ZwokRN_iwisXhHxI successfully fetched!
392, ChIJ6bXru69ZwokRQQ77x79D89M successfully fetched!
402, ChIJiag-Wq5ZwokRF7-3vlvEWJQ successfully fetched!
417, ChIJKUvC6K1ZwokR-6gilCP_YRg successfully fetched!

## View current results

In [121]:
restaurant_metadata = pd.read_csv('google_api_restaurant_metadata_step2.csv')
restaurant_popular_time = pd.read_csv('google_api_restaurant_popular_time_step2.csv')

In [122]:
restaurant_metadata[restaurant_metadata['popular_data'] == True]['place_id'].unique()

array(['ChIJRdi1GaxZwokR3vmYZ_GDcSM', 'ChIJV0bfnqtZwokRo0b29CRqsS8',
       'ChIJR751tVNu4oYRGQbCiV0obhs', 'ChIJASwLqU9ZwokRAoIgy6k2RgY',
       'ChIJ2VhDH6lZwokR_acLQfV63Tc', 'ChIJDUiwlK9ZwokRgEzA-oCI9a4',
       'ChIJ30krXK5ZwokRN_iwisXhHxI', 'ChIJ6bXru69ZwokRQQ77x79D89M',
       'ChIJiag-Wq5ZwokRF7-3vlvEWJQ', 'ChIJKUvC6K1ZwokR-6gilCP_YRg'],
      dtype=object)

In [123]:
restaurant_metadata[restaurant_metadata['popular_data'] == True].head()

,full_name,place_id,name,rating,review_count,address,lat,lon,types,opening_hours,...,phone,reviews,Latitude,Longitude,rough_lat,rough_lng,clustered,time_spent_min,time_spent_max,popular_data
107,ANDREW'S NYC DINER 463 7 AVENUE,ChIJRdi1GaxZwokR3vmYZ_GDcSM,Andrews NYC Diner,4.4,8048.0,"463 7th Ave, New York, NY 10018, USA",40.7517,-73.9898,"restaurant,food,point_of_interest,establishment",Monday: 6:00 AM – 10:00 PM; Tuesday: 6:00 AM –...,...,+1 212-695-1962,"[{'author_name': 'Dibo Goodman G7', 'author_ur...",40.7517,-73.9901,40.75,-73.99,True,60.0,60.0,True
145,ARNO RISTORANTE 141 WEST 38 STREET,ChIJV0bfnqtZwokRo0b29CRqsS8,Arno,4.4,865.0,"Arno Ristorante, 141 W 38th St, New York, NY 1...",40.7534,-73.9880,"bar,restaurant,food,point_of_interest,establis...",Monday: 11:45 AM – 10:00 PM; Tuesday: 11:45 AM...,...,+1 212-944-7420,"[{'author_name': 'Rachel Shalit', 'author_url'...",40.7531,-73.9877,40.75,-73.99,True,180.0,180.0,True
172,HAN BAT RESTAURANT 53 WEST 35 STREET,ChIJR751tVNu4oYRGQbCiV0obhs,Han Bat,4.0,960.0,"53 W 35th St, New York, NY 10001, USA",40.7502,-73.9863,"restaurant,food,point_of_interest,establishment",Monday: 11:30 AM – 10:30 PM; Tuesday: 11:30 AM...,...,+1 212-629-5588,"[{'author_name': 'Hyekyung Kim', 'author_url':...",40.7499,-73.9859,40.75,-73.99,True,NaN,NaN,True
175,LAZZARA'S PIZZA CAFE & RESTAURANT 221 WEST 3...,ChIJASwLqU9ZwokRAoIgy6k2RgY,Lazzara's Pizza Cafe,4.3,965.0,"221 W 38th St #2, New York, NY 10018, USA",40.7540,-73.9895,"restaurant,point_of_interest,food,establishment",Monday: 11:30 AM – 9:00 PM; Tuesday: 11:30 AM ...,...,+1 212-944-7792,"[{'author_name': 'Cristina Padilla', 'author_u...",40.7539,-73.9896,40.75,-73.99,True,90.0,90.0,True
245,RICK'S CABARET 50 WEST 33 STREET,ChIJ2VhDH6lZwokR_acLQfV63Tc,Rick's Cabaret New York,4.4,665.0,"50 W 33rd St, New York, NY 10001, USA",40.7486,-73.9874,"restaurant,food,point_of_interest,establishment",NaN,...,+1 212-372-0850,NaN,40.7486,-73.9872,40.75,-73.99,True,NaN,NaN,True

In [124]:
restaurant_popular_time['place_id'].unique()

array(['ChIJ03By9lhYwokRfGgIPEcxNlM', 'ChIJRdi1GaxZwokR3vmYZ_GDcSM',
       'ChIJV0bfnqtZwokRo0b29CRqsS8', 'ChIJR751tVNu4oYRGQbCiV0obhs',
       'ChIJASwLqU9ZwokRAoIgy6k2RgY', 'ChIJ30krXK5ZwokRN_iwisXhHxI',
       'ChIJ6bXru69ZwokRQQ77x79D89M'], dtype=object)